### ISSUE TITLE
Plans to open source the closed exam dataset?

### ISSUE THREAD

**Issue by Switchsyj** [mandyyyyii/scibench#1]
Hi, thanks for the meaningful work evaluating LLMs reasoning capabilities first. As mentioned in this paper, I guess the origin folder  refer to the open textbook dataset. I would like to know are there any plans to open source closed exam dataset?
Thanks!

**Comment by mandyyyyii** [comment]
Thank you for your interest in our project. I am sorry, but we don't have plans to open-source the closed exam dataset, since those exams are reserved for future course exam purposes.
