### ISSUE TITLE
Questions about zero-shot test

### ISSUE THREAD

**Issue by xuyifan-0731** [mandyyyyii/scibench#3]
According to your code, zero-shot setting(python eval_zero.py)  does not have sys_prompt(eval/eval_zero.py,line78). How the model gave proper answer in \boxed{} without any instructions? In paper, GPT-4 get 25.09 .

Another strange problem (probably a code error) is that the parse_math_answer function does not return any value, which makes all experiments impossible.
post_process.py
```
def parse_math_answer(raw_string):
    remove_boxed(last_boxed_only_string(raw_string))
```

**Comment by mandyyyyii** [comment]
We have two versions for zero-shot setting. The setting that got 25.09 uses the system prompt. We have another setting in the table called 'ZERO-S', which doesn't use system prompt, where we manually extract answer from the model output. If you want to run zero-shot setting with system prompt, you could add "--sys" in the command. 

For second issue, we just update the code to address it. Please let me know if there is anything else that needs to be addressed.
