### ISSUE TITLE
[Bug] Some problems include the extra information in the textbook.

### ISSUE THREAD

**Issue by LinxinS97** [mandyyyyii/scibench#5]
For example:
Using the explicit formulas for the Hermite polynomials `given in Table 5.3`, show that a $0 \rightarrow 1$ vibrational transition is allowed and that a $0 \rightarrow 2$ transition is forbidden.

The information in Table 5.3 has not been included in the dataset.

**Comment by mandyyyyii** [comment]
We have updated our dataset for this issue. Thank you for your information.
