### ISSUE TITLE
Information mismatch between problem statement and solution

### ISSUE THREAD

**Issue by BorjaRequena** [mandyyyyii/scibench#6]
Hi! I am going through some of the problems in the collection and I stumbled upon problem 10.11 in `dataset/original/fund_sol.json` (it's the 3rd there). The problem states that there is a disk mounted on a fixed horizontal axle with a hanging block from a cord wrapped around the rim of the disk. The disk starts at rest with an angular acceleration of $\alpha = -24 \mathrm{rad/s}^2$ and the mass produces a tension of $T = 6\mathrm{N}$. Then, it asks for the rotational kinetic energy $K$ at $t=2.5 \mathrm{~s}$.

In the problem statement, there is no information about the mass of the disk or its radius. Nevertheless, the solution makes extensive use of it to compute the result, using the relationships $K=\frac{1}{2}I\omega^2$ and $I=\frac{1}{2}mr^2$. The solution assigns $m=2.5 \\mathrm{kg}$ and $r=0.2\\mathrm{m}$, which are not provided in the problem statement.

Given the problem description, it'd be expected to use the tension to compute the moment of inertia from the torque $\tau = I \alpha$, where the torque $\tau = Tr$. This approach still needs the radius though. Indeed, if one assumes $T = I \alpha$ the resulting $I$ is 5 times larger than it should, indicating that the radius is, indeed, $r = 0.2\mathrm{m}$. 

Could the problem statement not be complete?

**Comment by mandyyyyii** [comment]
Thanks for your information. This problem refers to a previous problem and I have added the condition mentioned from the previous problem and updated the file. Please let me know if there is any other question.

**Comment by BorjaRequena** [comment]
That's great, thanks! 😄

**Comment by BorjaRequena** [comment]
I have spotted problem 9.03 in the same file that requires an image to know the masses of the particles (I assume?) and the directions of the forces they are feeling. Could it be?

The dataset is great, and I greatly appreciate the effort that you've put into it. I believe it has a lot of potential as a benchmark that can allow us to evaluate the reasoning capabilities for scientific applications separated by fields. However, in order for it to become a reliable benchmark, I believe it could use an overall review given that 2 out of the 8 problems I've gone through are missing essential information to be solved 😅

**Comment by mandyyyyii** [comment]
The image is provided at dataset/img/problem_solution/25.

**Comment by BorjaRequena** [comment]
Oh, I see. I understood that only the problems within `dataset/img/` were the ones that required images to be solved and that those in `dataset/original` where text-only problems. When looking for a text-only assessment, what is the correct way to detect whether a problem inside `dataset/original` requires an associated image and locate it in the `dataset/img/` folder? 

For instance, in this case, where can I find that problem 9.03 inside `dataset/img/fund_sol.json` requires an image found in `dataset/img/problem_solution/25/img_question.png`?

**Comment by mandyyyyii** [comment]
You could consider using a string comparison to filter out. We'll create a dedicated folder for this purpose at a later stage.
